version: '3.9'
services:
  single_database:
    env_file:
      - ./.env.single
    image: single-database:latest
    container_name: single-database
    restart: on-failure
    build:
      context: ./single-database-multi-tenancy/
      dockerfile: Dockerfile
    ports:
      - 5002:80
      - 5003:443
    volumes:
      - ./certificate:/app/certificate
      - ./single-database-multi-tenancy/temp-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Certificates__Default__Password=1234
      - Kestrel__Certificates__Default__Path=/app/certificate/certificate.pfx
    networks:
      - multi_tenancy_net

  isolated_databases:
    env_file:
      - ./.env.isolated
    image: isolated-databases:latest
    container_name: isolated-databases
    restart: on-failure
    build:
      context: ./isolated-databases-multi-tenancy/
      dockerfile: Dockerfile
    ports:
      - 5004:80
      - 5005:443
    volumes:
      - ./certificate:/app/certificate
      - ./isolated-databases-multi-tenancy/temp-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Certificates__Default__Password=1234
      - Kestrel__Certificates__Default__Path=/app/certificate/certificate.pfx
    networks:
      - multi_tenancy_net

networks:
  multi_tenancy_net:
    name: multi_tenancy_net