// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SingleDatabaseMultiTenancy.Data.Context;

#nullable disable

namespace SingleDatabaseMultiTenancy.Data.Migrations
{
    [DbContext(typeof(SingleDatabaseMultiTenancyContext))]
    partial class SingleDatabaseMultiTenancyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SingleDatabaseMultiTenancy.Domain.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1dfc4a8d-7ed1-443c-9cc7-ac71ea9d003b"),
                            Nome = "Cachorro",
                            Tenant = "Tenant01"
                        },
                        new
                        {
                            Id = new Guid("8b5c8482-f2ec-4cf6-aaa8-20ec25112cd7"),
                            Nome = "Hamster",
                            Tenant = "Tenant02"
                        });
                });

            modelBuilder.Entity("SingleDatabaseMultiTenancy.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d78a657f-66fa-43f2-a535-212e6bfb6630"),
                            Login = "Teste01",
                            Nome = "Teste 01",
                            Senha = "1234",
                            Tenant = "Tenant01"
                        },
                        new
                        {
                            Id = new Guid("10b42acc-45bd-460a-9edd-d568ff236e37"),
                            Login = "Teste02",
                            Nome = "Teste 02",
                            Senha = "4567",
                            Tenant = "Tenant02"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
